import {
  User, WorkerNode, Job, CapacitySnapshot, Approval, AuditEvent
} from '../types';

export const INITIAL_USER: User = {
  id: 'usr_admin_001',
  username: 'admin',
  email: 'admin@localcompute.commons',
  full_name: 'Cluster Operator',
  role: 'admin',
  organization_id: 'org_commons_mesh'
};

export const INITIAL_NODES: WorkerNode[] = [
  {
    id: 'node-alpha-4090',
    node_id: 'node-alpha-4090',
    node_name: 'Compute-Rig-Alpha (RTX 4090)',
    organization_id: 'lab-secure-01',
    status: 'online',
    trust_level: 'trusted_lab',
    is_localhost: false,
    is_airgapped: false,
    capabilities: {
      cpu_cores: 32,
      cpu_utilization_pct: 28.5,
      memory_mb: 65536,
      memory_available_mb: 46200,
      gpu_name: 'NVIDIA GeForce RTX 4090 24GB',
      vram_mb: 24576,
      vram_available_mb: 18432,
      os_name: 'Linux (Ubuntu 24.04 LTS)',
      os_version: '6.8.0-generic',
      cached_models: ['llama3-8b-instruct', 'mistral-7b-v0.3', 'nomic-embed-text-v1.5'],
      power_state: 'ac_power',
      network_mbps: 1000,
      clock_skew_ms: 1.2,
    },
    registered_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    last_heartbeat_at: new Date().toISOString(),
    active_leases_count: 2,
  },
  {
    id: 'node-bravo-m3',
    node_id: 'node-bravo-m3',
    node_name: 'MacStudio-M3-Max (Unified Memory)',
    organization_id: 'commons-peer',
    status: 'online',
    trust_level: 'community',
    is_localhost: false,
    is_airgapped: false,
    capabilities: {
      cpu_cores: 16,
      cpu_utilization_pct: 14.2,
      memory_mb: 131072,
      memory_available_mb: 98304,
      gpu_name: 'Apple M3 Max 40-core GPU',
      vram_mb: 98304,
      vram_available_mb: 73728,
      os_name: 'macOS Sonoma',
      os_version: '14.5 (Darwin 23.5.0)',
      cached_models: ['llama3-70b-q4', 'phi-3-mini', 'bge-large-en'],
      power_state: 'ac_power',
      network_mbps: 2500,
      clock_skew_ms: 0.8,
    },
    registered_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    last_heartbeat_at: new Date().toISOString(),
    active_leases_count: 1,
  },
  {
    id: 'node-charlie-airgap',
    node_id: 'node-charlie-airgap',
    node_name: 'Secure-Vault-Airgapped (Local Node)',
    organization_id: 'internal-vault',
    status: 'online',
    trust_level: 'airgapped',
    is_localhost: true,
    is_airgapped: true,
    capabilities: {
      cpu_cores: 24,
      cpu_utilization_pct: 9.1,
      memory_mb: 65536,
      memory_available_mb: 58200,
      gpu_name: 'NVIDIA RTX A6000 48GB',
      vram_mb: 49152,
      vram_available_mb: 44000,
      os_name: 'Rocky Linux',
      os_version: '9.4 (Airgapped Profile)',
      cached_models: ['llama3-8b-instruct', 'starcoder2-15b'],
      power_state: 'ups_isolated',
      network_mbps: 0,
      clock_skew_ms: 0.2,
    },
    registered_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    last_heartbeat_at: new Date().toISOString(),
    active_leases_count: 0,
  },
  {
    id: 'node-delta-xeon',
    node_id: 'node-delta-xeon',
    node_name: 'Edge-Cluster-Xeon-128',
    organization_id: 'datacenter-east',
    status: 'paused',
    trust_level: 'trusted_lab',
    is_localhost: false,
    is_airgapped: false,
    capabilities: {
      cpu_cores: 64,
      cpu_utilization_pct: 4.0,
      memory_mb: 262144,
      memory_available_mb: 240000,
      gpu_name: 'NVIDIA L40S 48GB',
      vram_mb: 49152,
      vram_available_mb: 48000,
      os_name: 'Debian GNU/Linux',
      os_version: '12 (Bookworm)',
      cached_models: ['llama3-70b-q4', 'mistral-large'],
      power_state: 'ac_power',
      network_mbps: 10000,
      clock_skew_ms: 0.4,
    },
    registered_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    last_heartbeat_at: new Date(Date.now() - 120000).toISOString(),
    active_leases_count: 0,
  },
];

export const INITIAL_SNAPSHOT: CapacitySnapshot = {
  total_nodes: 4,
  online_nodes: 3,
  paused_nodes: 1,
  total_cpu_cores: 136,
  available_cpu_cores: 104,
  total_memory_gb: 512,
  available_memory_gb: 432,
  total_vram_gb: 220,
  available_vram_gb: 184,
  cached_models_summary: {
    'llama3-8b-instruct': 2,
    'llama3-70b-q4': 2,
    'mistral-7b-v0.3': 1,
    'nomic-embed-text-v1.5': 1,
    'starcoder2-15b': 1,
  },
  active_jobs: 3,
  pending_tasks: 1,
  running_tasks: 2,
  avg_queue_wait_seconds: 1.4,
  snapshot_time: new Date().toISOString(),
};

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-98a41c22',
    workload_id: 'wl_finance_audit_batch',
    user_id: 'usr_admin_001',
    title: 'Financial Q3 Disclosure Privacy Extraction',
    state: 'running',
    privacy_class: 'local_only',
    required_model: 'llama3-8b-instruct',
    priority: 9,
    total_tasks: 8,
    pending_tasks: 1,
    running_tasks: 2,
    succeeded_tasks: 5,
    failed_tasks: 0,
    created_at: new Date(Date.now() - 360000).toISOString(),
    updated_at: new Date().toISOString(),
    scheduling_explanation: {
      job_id: 'job-98a41c22',
      selected_node_id: 'node-charlie-airgap',
      selected_node_name: 'Secure-Vault-Airgapped (Local Node)',
      total_score: 96.4,
      policy_version: '2026.1-privacy-strict',
      requires_approval: false,
      generated_at: new Date(Date.now() - 355000).toISOString(),
      factors: [
        {
          factor_name: 'Airgap & Local Privacy Match',
          raw_value: 'Matched local_only constraint',
          weight: 0.45,
          contribution: 45.0,
          description: 'Job requested strict local-only execution; node is 100% air-gapped with zero egress.',
        },
        {
          factor_name: 'Model Warm Cache',
          raw_value: 'llama3-8b-instruct cached',
          weight: 0.30,
          contribution: 30.0,
          description: 'Required model weights pre-loaded in VRAM, eliminating 4.2GB model transfer overhead.',
        },
        {
          factor_name: 'Available VRAM Headroom',
          raw_value: '44GB free',
          weight: 0.25,
          contribution: 21.4,
          description: '44.0 GB free VRAM exceeds the 8.5 GB required allocation limit.',
        },
      ],
      excluded_nodes: [
        {
          node_id: 'node-bravo-m3',
          node_name: 'MacStudio-M3-Max (Unified Memory)',
          reason: 'Node is community trust tier, which does not satisfy local_only strict confidentiality.',
          violates_constraint: 'privacy_tier_constraint',
        },
      ],
    },
    tasks: [
      {
        id: 'task-98a41c22-01',
        job_id: 'job-98a41c22',
        sequence_num: 1,
        state: 'succeeded',
        assigned_node_id: 'node-charlie-airgap',
        assigned_node_name: 'Secure-Vault-Airgapped',
        attempt_count: 1,
        max_retries: 3,
        input_payload: { chunk_id: 1, token_count: 1420 },
        output_payload: { status: 'redacted_clean', entities_scrubbed: 14 },
        result_checksum: 'sha256:8f2a9e102f...c38b',
        started_at: new Date(Date.now() - 350000).toISOString(),
        completed_at: new Date(Date.now() - 290000).toISOString(),
      },
      {
        id: 'task-98a41c22-02',
        job_id: 'job-98a41c22',
        sequence_num: 2,
        state: 'running',
        assigned_node_id: 'node-charlie-airgap',
        assigned_node_name: 'Secure-Vault-Airgapped',
        attempt_count: 1,
        max_retries: 3,
        input_payload: { chunk_id: 2, token_count: 2180 },
        started_at: new Date(Date.now() - 140000).toISOString(),
      },
    ],
  },
  {
    id: 'job-17e94b01',
    workload_id: 'wl_research_synthesis_m3',
    user_id: 'usr_admin_001',
    title: 'Distributed Vector Embeddings & Graph Build',
    state: 'succeeded',
    privacy_class: 'trusted_nodes',
    required_model: 'bge-large-en',
    priority: 7,
    total_tasks: 16,
    pending_tasks: 0,
    running_tasks: 0,
    succeeded_tasks: 16,
    failed_tasks: 0,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 6800000).toISOString(),
    completed_at: new Date(Date.now() - 6800000).toISOString(),
    aggregated_result: 'Successfully indexed 16 documents across 48,290 embeddings into vector store.',
  },
];

export const INITIAL_APPROVALS: Approval[] = [
  {
    id: 'appr-7701-airgap-lease',
    action: 'allocate_high_vram_lease',
    requester_user_id: 'usr_dev_04',
    requester_username: 'sarah.analyst',
    target_id: 'node-charlie-airgap',
    target_type: 'worker_node',
    reason: 'Requesting exclusive 40GB VRAM lease on air-gapped node for confidential customer dataset sanitization.',
    parameters: {
      node_id: 'node-charlie-airgap',
      lease_duration_minutes: 60,
      vram_requested_mb: 40960,
    },
    status: 'pending',
    created_at: new Date(Date.now() - 1800000).toISOString(),
    expires_at: new Date(Date.now() + 5400000).toISOString(),
  },
];

export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'aud_f8301c',
    event_type: 'WORKLOAD_SCHEDULED',
    actor_id: 'scheduler.autonomous',
    actor_role: 'operator',
    target_type: 'job',
    target_id: 'job-98a41c22',
    action_details: {
      assigned_node: 'node-charlie-airgap',
      privacy_class: 'local_only',
      score: 96.4,
    },
    ip_address: '127.0.0.1',
    event_hash: '3a7b9c1d8e5f2a4b0c6d7e8f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
    timestamp: new Date(Date.now() - 355000).toISOString(),
  },
  {
    id: 'aud_e4210a',
    event_type: 'NODE_HEARTBEAT_VERIFIED',
    actor_id: 'node-bravo-m3',
    actor_role: 'worker',
    target_type: 'worker_node',
    target_id: 'node-bravo-m3',
    action_details: {
      vram_available_mb: 73728,
      latency_ms: 12,
      trust_level: 'community',
    },
    ip_address: '192.168.1.144',
    event_hash: '6d7e8f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e',
    timestamp: new Date(Date.now() - 420000).toISOString(),
  },
  {
    id: 'aud_d1194f',
    event_type: 'APPROVAL_REQUESTED',
    actor_id: 'usr_dev_04',
    actor_role: 'user',
    target_type: 'approval',
    target_id: 'appr-7701-airgap-lease',
    action_details: {
      reason: 'Air-gapped 40GB VRAM lease request',
      expires_minutes: 120,
    },
    ip_address: '10.0.4.19',
    event_hash: '9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
  },
];
